ORMBundle\Entity\Ips:
    type: entity
    table: ips
    indexes:
        id_origine:
            columns:
                - id_origine
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idOrigine:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_origine
        ip:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
    lifecycleCallbacks: {  }
