ORMBundle\Entity\PageSpeed:
    type: entity
    table: page_speed
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        desktop:
            type: float
            nullable: true
            precision: 10
            scale: 0
        mobile:
            type: float
            nullable: true
            precision: 10
            scale: 0
        oldMobile:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: old_mobile
        oldDesktop:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: old_desktop
        lastUpdate:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: last_update
    lifecycleCallbacks: {  }
