ORMBundle\Entity\Registrar:
    type: entity
    table: registrar
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        login:
            type: string
            nullable: false
            length: 6000
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 6000
            options:
                fixed: false
        dns1:
            type: string
            nullable: false
            length: 6000
            options:
                fixed: false
        dns2:
            type: string
            nullable: false
            length: 6000
            options:
                fixed: false
        adminserveur:
            type: string
            nullable: false
            length: 6000
            options:
                fixed: false
            column: adminServeur
        prix:
            type: string
            nullable: false
            length: 6000
            options:
                fixed: false
        commentaire:
            type: string
            nullable: false
            length: 6000
            options:
                fixed: false
        url:
            type: string
            nullable: false
            length: 6000
            options:
                fixed: false
                comment: 'url de login'
        mail:
            type: string
            nullable: false
            length: 6000
            options:
                fixed: false
                comment: 'mail de contact'
        nextUpdateDomain:
            type: datetime
            nullable: true
            column: next_update_domain
    lifecycleCallbacks: {  }
