ORMBundle\Entity\TemporaryUrl:
    type: entity
    table: temporary_url
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        url:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        mobile:
            type: float
            nullable: true
            precision: 10
            scale: 0
        desktop:
            type: float
            nullable: true
            precision: 10
            scale: 0
    lifecycleCallbacks: {  }
