ORMBundle\Entity\TypeProjet:
    type: entity
    table: type_projet
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        value:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
    lifecycleCallbacks: {  }
